#%RAML 1.0 NamedExample
value:
  preferredRetailer: 00x123122227777777
  salutation: Ms
  firstName: Emma
  lastName:  Watson
  email: emma.watson@gmail.com
  phone: 9090909090
  preferredDateTime: 2015-07-04T21:00:00
  emailConsent: True
  phoneConsent: True
  SMSConsent: True
  market: US
  modelOfInterest : 00x234wwejrTT4433
  address:
    countryCode : US